apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'flask-service'
        static_configs:
          - targets: ['flask-service:80']

    alerting:
      alertmanagers:
        - static_configs:
          - targets: ['alertmanager-config:9093']
