apiVersion: v1
kind: Pod
metadata:
  name: alert-simulation-pod
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9100"  
spec:
  containers:
  - name: metrics-server
    image: prom/node-exporter
    ports:
    - containerPort: 9100 
  - name: crash-container
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 60 && exit 1"]
